import { createClient } from "npm:@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
};

/**
 * Inbound Mailchimp webhook. Public — verify_jwt=false.
 * Auth is a shared secret in the `?s=` query param, generated by
 * mailchimp-bootstrap and stored in app_config. Mailchimp does not sign
 * webhook bodies; this is the accepted pattern.
 *
 * Mailchimp GETs the URL first to validate; respond 200 to any GET.
 * On POST, forms come as application/x-www-form-urlencoded with fields like
 *   type=subscribe|unsubscribe|profile|upemail|cleaned
 *   data[email]=..., data[list_id]=..., data[new_email]=...
 */

async function readFormData(req: Request): Promise<Record<string, string>> {
  const ct = req.headers.get("content-type") || "";
  const out: Record<string, string> = {};
  if (ct.includes("application/json")) {
    const j = await req.json().catch(() => ({}));
    // Flatten data[email] etc for uniform access
    for (const [k, v] of Object.entries(j)) {
      if (typeof v === "object" && v !== null) {
        for (const [k2, v2] of Object.entries(v as Record<string, unknown>)) {
          out[`${k}[${k2}]`] = String(v2 ?? "");
        }
      } else out[k] = String(v ?? "");
    }
    return out;
  }
  const body = await req.text();
  const params = new URLSearchParams(body);
  for (const [k, v] of params.entries()) out[k] = v;
  return out;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  const url = new URL(req.url);
  const providedSecret = url.searchParams.get("s") || "";

  const admin = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
  );

  const { data: cfg } = await admin
    .from("app_config").select("value").eq("key", "mailchimp_webhook").maybeSingle();
  const expected = cfg?.value?.secret;
  if (!expected || providedSecret.length < 16 || providedSecret !== expected) {
    return new Response("forbidden", { status: 403, headers: corsHeaders });
  }

  // Mailchimp verification ping
  if (req.method === "GET") return new Response("ok", { status: 200, headers: corsHeaders });
  if (req.method !== "POST") return new Response("method not allowed", { status: 405, headers: corsHeaders });

  let form: Record<string, string> = {};
  try { form = await readFormData(req); } catch { return new Response("bad body", { status: 400, headers: corsHeaders }); }

  const type = form["type"];
  const email = (form["data[email]"] || "").toLowerCase().trim();
  const newEmail = (form["data[new_email]"] || "").toLowerCase().trim();

  try {
    if (type === "unsubscribe" || type === "cleaned") {
      if (email) {
        await admin.from("profiles").update({ marketing_opt_in: false }).eq("email", email);
      }
    } else if (type === "subscribe") {
      if (email) {
        await admin.from("profiles").update({ marketing_opt_in: true }).eq("email", email);
      }
    } else if (type === "upemail") {
      if (email && newEmail) {
        await admin.from("profiles").update({ email: newEmail }).eq("email", email);
      }
    }
    // 'profile' updates are informational only
  } catch (e) {
    console.error("[mailchimp-webhook] update failed", e);
  }

  return new Response("ok", { status: 200, headers: corsHeaders });
});